Return a non-null value from the sync update method
This is a follow-on to
01f788e464cc11efd13777b0046fa00fd1468c27

If we don't do this, then the CommunicationHelper code that expects to parse
the result fails (see below) and we get an exception.

https://github.com/e-mission/cordova-server-communication/blob/master/src/ios/BEMCommunicationHelperPlugin.m#L20

```
            NSDictionary *parsedResult = [NSJSONSerialization JSONObjectWithData:data
                                                                options:kNilOptions
                                                                  error: &parseError];

```